### ISSUE TITLE
production broken

### ISSUE THREAD

**Issue by connor11528** [vtange/nightlifemap#1]
error in the console for heroku deploy, map does not render

```
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
angular.js:4413Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=NightLifeMap&p1=Err…ogleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.7%2Fangular.min.js%3A19%3A463)
https://nightlifemap.herokuapp.com/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by vtange** [comment]
Thanks for the heads up. I'll look into this when I finish with my current project.

The map renders for me on Firefox 45.0b6. I'll poke around and see if it's a browser issue.

**Comment by connor11528** [comment]
Found using Chrome

**Comment by vtange** [comment]
Seems to work now that I added strict-mode to the client-side JS. Funny how FF allows me to use ES6 but Chrome doesn't unless I use strict-mode.
